#!/usr/bin/env bash

# sway-get-workspace
#  - Print name of current workspace

shopt -s xpg_echo

bold="\033[1m"
green="\033[32m"
reset="\033[0m"

# print usage message on -h/--help
if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
  echo "${bold}Usage:${reset} ${green}sway-get-current-workspace${reset}"
  echo "  - Print name of current workspace"
  exit 0
fi

# swaymsg, fallback to i3-msg
swaymsg() {
  if command -v swaymsg >/dev/null 2>&1; then
    command swaymsg "$@"
  else
    command i3-msg "$@"
  fi
}

# get number of first empty workspace to the right of the current one
workspaces=$(swaymsg -t get_workspaces)
current_workspace=$(echo "${workspaces}" | jq '.[] | select(.focused==true).num')

echo "${current_workspace}"
